In [1]:
import numpy

numpy.__version__

'2.2.3'

In [2]:
array_x = numpy.arange(9).reshape(3, 3)
array_x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
array_x.strides

(24, 8)

In [5]:
array_y = array_x[::2, ::2]
array_y

array([[0, 2],
       [6, 8]])

In [6]:
array_y.strides

(48, 16)

In [7]:
array_y[0, 0] = 100
array_x

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [8]:
array_x_transposed = array_x.T
array_x_transposed

array([[100,   3,   6],
       [  1,   4,   7],
       [  2,   5,   8]])

In [9]:
array_x_transposed.strides

(8, 24)

In [10]:
array_z = array_x.reshape(1, 9)
array_z

array([[100,   1,   2,   3,   4,   5,   6,   7,   8]])

In [11]:
array_z.strides

(72, 8)

In [12]:
array_z.dtype = numpy.dtype('uint8')
array_z

array([[100,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,
          0,   0,   0,   2,   0,   0,   0,   0,   0,   0,   0,   3,   0,
          0,   0,   0,   0,   0,   0,   4,   0,   0,   0,   0,   0,   0,
          0,   5,   0,   0,   0,   0,   0,   0,   0,   6,   0,   0,   0,
          0,   0,   0,   0,   7,   0,   0,   0,   0,   0,   0,   0,   8,
          0,   0,   0,   0,   0,   0,   0]], dtype=uint8)

In [13]:
array_z.shape

(1, 72)

In [14]:
array_z.strides

(72, 1)