In [1]:
import numpy
array1 = numpy.zeros(3)
array1

array([0., 0., 0.])

In [2]:
array1.shape

(3,)

In [7]:
array1.shape = (1,3)
array1

array([[0., 0., 0.]])

In [8]:
array1.shape

(1, 3)

In [9]:
array1.shape = (3,1)
array1

array([[0.],
       [0.],
       [0.]])

In [10]:
array1.shape

(3, 1)

In [12]:
array2 = numpy.ones(10)
array2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
array3 = numpy.empty(3)
array3

array([0.00000000e+000, 2.12199579e-314, 6.36598737e-314])

In [ ]:
array4 = numpy.linspace(2, 10, 5) # 5 numbers between 2 and 10 (both included) which are evenly distributed 
array4

array([ 2.,  4.,  6.,  8., 10.])