In [1]:
import numpy as np
np.version.full_version

'2.2.3'

In [2]:
a = np.array([0, 1, 2, 3, 4, 5])
type(a)

numpy.ndarray

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a.ndim

1

In [5]:
a.shape

(6,)

In [6]:
b = a.reshape((3, 2))
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
b.ndim

2

In [8]:
b.shape

(3, 2)

In [9]:
b[1][0]=77
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [ ]:
# Changing the value of "b" has also changed the value of "a" :
a

array([ 0,  1, 77,  3,  4,  5])

In [11]:
# Here, "c" is a completely independent copy of "a".
c = a.reshape((3, 2)).copy()
c

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [12]:
c[0][0] = -99
c

array([[-99,   1],
       [ 77,   3],
       [  4,   5]])

In [13]:
# Change to "c" has not changed anything in "a".
a

array([ 0,  1, 77,  3,  4,  5])