In [1]:
import numpy as np

a = np.array([1, 2, 3, 3, 8, 4, 7, 5, 6]).reshape((3, 3))
a

array([[1, 2, 3],
       [3, 8, 4],
       [7, 5, 6]])

In [ ]:
# A new matrix with elements of a which were greater than 4

filtered_a = a[a>4]
filtered_a

array([8, 7, 5, 6])

In [ ]:
a[a > 4] = 0
a

array([[1, 2, 3],
       [3, 0, 4],
       [0, 0, 0]])

In [5]:
b = np.array([1, 2, 3, 3, 8, 4, 7, 5, 6, 8, 3, 7, 4, 6, 5, 3, 4, 0, 8, 9, 6, 5, -23, 7]).reshape((4, 6))
b


array([[  1,   2,   3,   3,   8,   4],
       [  7,   5,   6,   8,   3,   7],
       [  4,   6,   5,   3,   4,   0],
       [  8,   9,   6,   5, -23,   7]])

In [6]:
b.clip(1, 5)

array([[1, 2, 3, 3, 5, 4],
       [5, 5, 5, 5, 3, 5],
       [4, 5, 5, 3, 4, 1],
       [5, 5, 5, 5, 1, 5]])